### ISSUE TITLE
Sth-Comet does not reconnect with MongoDB.

### ISSUE THREAD

**Issue by SwatiNEC** [telefonicaid/fiware-sth-comet#559]
**Issue Description:**
When Mongodb restarted, STH-Comet and MongoDB are disconnected and will not reconnect. API responds normally even though the connection with MongoDB is lost, so the user don't know that an error has occurred. Shouldn't the API respond with an error ? 
And it is not possible to know from the log that the connection with MongoDB has been lost. Shouldn't it be output that the connection was lost in the error log ?
Connection is not restored even if MongoDB is restored. Shouldn't it reconnect ?

**Reproduction Steps:**
1 Store the history data in MongoDB
2 Start STH-Comet and MongoDB
3 Execute the API on STH-Comet and confirm that you can get the history data.
4 Stop only MongoDB and restart MongoDB after 5 minutes 
5 Execute the API on STH-Comet and confirm that you cannot get the history data (status: 200OK but values field will be empty).

**API used for getting history data:**
curl -X GET 'localhost:8666/STH/v1/contextEntities/type/Room/id/Room1/attributes/temperature?lastN=1' -H 'fiware-service: test' -H 'fiware-servicePath: /'

**Output:** 
{"contextResponses":[{"contextElement":{"attributes":[{"name":"temperature","values":[]}],"id":"Room1","isPattern":false,"type":"Room"},"statusCode":{"code":"200","reasonPhrase":"OK"}}]}

**Expected output:**
{"contextResponses":[{"contextElement":{"attributes":[{"name":"temperature","values":[{"recvTime":"2021-09-17T08:06:25.046Z","attrType":"string","attrValue":"190"}]}],"id":"Room1","isPattern":false,"type":"Room"},"statusCode":{"code":"200","reasonPhrase":"OK"}}]}

**Comment by SwatiNEC** [comment]
Hi @fgalan 

As per our understanding, It seems a bug. Please share your opinion.

**Comment by SwatiNEC** [comment]
Could anyone please confirm whether it is a bug or it is a specification of sth-comet.

**Comment by fgalan** [comment]
We'll have a look. Thanks for the feedback!

**Comment by mapedraza** [comment]
I confirm I could reproduce the problem @SwatiNEC commented. 

Additional information:
- STH Version: Latest (2.8.0)

Procedure: 
1. Bring up the containers
2. Create the subscription
3. Create the entity
4. Modify the entity several times
5. Get historical data from STH - Everything works well
6. Stop MongoDB container for a while
7. Resume the same container
8. Get historical data - Empty log but a response code 200

The log is printing this:
``` LOG
fiware-sth-comet | time=2021-09-28T13:14:32.347Z | lvl=WARN | corr=0616e74d-914d-447e-ba52-747fa3dbe9bc | trans=0616e74d-914d-447e-ba52-747fa3dbe9bc | op=OPER_STH_GET | from=n/a | srv=test | subsrv=/ | comp=STH | msg=Error when getting the raw data collection for retrieval (the collection 'undefined' may not exist)
```

Complete log [here](https://gist.github.com/mapedraza/cb3fd743b1a470ca46ada9db8f253c1b)

Requests used:
**Create subscription**
```
curl -iX POST \
  --url 'http://localhost:1026/v2/subscriptions' \
  --header 'content-type: application/json' \
  -H 'fiware-service: test' -H 'fiware-servicePath: /' \
  --data '{
  "description": "HTTP sub",
  "subject": {
    "entities": [
      {
        "id": "E",
        "type": "T"
      }
    ]
  },
  "notification": {
    "http": {
      "url": "http://sth-comet:8666/notify"
    },
    "attrsFormat": "legacy"
  }
}'
```

**Create entity**
```
curl -iX POST \
  --url 'http://localhost:1026/v2/entities' \
  --header 'content-type: application/json' \
  -H 'fiware-service: test' -H 'fiware-servicePath: /' \
  --data '{
  "id": "E",
  "type": "T",
  "A": {
    "value": 1,
    "type": "Float"
  }
}'
```

**Update entity**
```
curl -iX POST --url 'http://localhost:1026/v2/entities/E/attrs' --header 'content-type: application/json' -H 'fiware-service: test' -H 'fiware-servicePath: /' --data '{"A":{"value": 2,"type": "Float"}}'
```

**Query STH***
```
curl -X GET 'localhost:8666/STH/v1/contextEntities/type/T/id/E/attributes/A?lastN=1' -H 'fiware-service: test' -H 'fiware-servicePath: /'
```

**docker-compose.yml**
```yml
version: "3.5"
services:
  orion:
    image: telefonicaiot/fiware-orion:3.2.0
    hostname: orion
    platform: linux/amd64
    container_name: fiware-orion
    depends_on:
      - mongo-db
    expose:
      - "1026"
    ports:
      - "1026:1026" 
    command: -dbhost mongo-db -logLevel DEBUG -mqttMaxAge 5

  mongo-db:
    image: mongo:4.4
    hostname: mongo-db
    platform: linux/amd64
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"

  sth-comet:
      image: fiware/sth-comet
      hostname: sth-comet
      container_name: fiware-sth-comet
      depends_on:
          - mongo-db
      ports:
          - "8666:8666"
      environment:
          - STH_HOST=0.0.0.0
          - STH_PORT=8666
          - DB_PREFIX=sth_
          - DB_URI=mongo-db:27017
          - LOGOPS_LEVEL=DEBUG
```
