### ISSUE TITLE
TRUNCATION_EXPIRE_AFTER_SECONDS doesn't work

### ISSUE THREAD

**Issue by ctc-watanabe** [telefonicaid/fiware-sth-comet#606]
I am running STH-comet in minimal mode.
The docker-compose.yml I used is as follows:

```
version: "3"

services:
  orion:
    container_name: orion
    image: fiware/orion:3.7.0
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel DEBUG

  sth:
    container_name: sth
    image: fiware/sth-comet:2.10.0
    links:
      - mongo
    ports:
      - "8666:8666"
    environment:
      - STH_HOST=0.0.0.0
      - DB_URI=mongo:27017
      - TRUNCATION_EXPIRE_AFTER_SECONDS=60
      - TRUNCATION_SIZE=1024
      - TRUNCATION_MAX=10

  mongo:
    container_name: mongo
    image: mongo:4.4
```

I created the following entity in Orion.

```
{
  "id":"Car1",
  "type":"Car",
  "speed":{
    "type":"Float",
    "value":98
  }
}
```

I have notified updates of the entity to STH-comet and confirmed that the historical data is created in mongo as follows:

```
{
    "type": "StructuredValue",
    "value": [
        {
            "_id": "6441ee51631ed700075458d0",
            "recvTime": "2023-04-21T02:00:49.925Z",
            "attrName": "speed",
            "attrType": "Float",
            "attrValue": 70
        },
        {
            "_id": "6441ef1e631ed700075458d1",
            "recvTime": "2023-04-21T02:04:14.385Z",
            "attrName": "speed",
            "attrType": "Float",
            "attrValue": 90
        },
        {
            "_id": "6441ef21631ed700075458d2",
            "recvTime": "2023-04-21T02:04:17.307Z",
            "attrName": "speed",
            "attrType": "Float",
            "attrValue": 60
        },
...
```

However, the environment variable "TRUNCATION_EXPIRE_AFTER_SECONDS" of STH-comet is set to 60, but the data remains in mongo after a minute.
"TRUNCATION_SIZE" and "TRUNCATION_MAX" seem to work.
Could you tell me if I have made a mistake or this is a bug?
